/* Parity tests: the JS engine must reproduce the Python engine (which is
 * itself validated against a real certified-software return) to the cent.
 * Run:  node engine.test.mjs
 */
import {
  computeReturn, computeTax, computeSchedule8, computeSchedule1,
  applyLosses, groundLimit, checkScope, halfUp,
} from "./engine.js";

let pass = 0, fail = 0;
function eq(label, got, want) {
  if (got === want) { pass++; }
  else { fail++; console.error(`FAIL ${label}: got ${got}, want ${want}`); }
}

const corp = (province = "BC", tyStart = "2025-01-01", tyEnd = "2025-12-31") =>
  ({ legalName: "CASE CORP.", province, tyStart, tyEnd });

const profitCase = (province, revenueCents, opts = {}) => computeReturn(
  corp(province, opts.start, opts.end),
  { revenue: revenueCents, openingInv: 0, purchases: 0, closingInv: 0,
    expenses: [], cash: revenueCents, shareCapital: 100_00, ...opts.fin });

// ---- rounding
eq("halfUp 2.5", halfUp(2.5), 3);
eq("halfUp -2.5 (away from zero)", halfUp(-2.5), -3);

// ---- Synthetic e-commerce year (fixture generated by the reference Python
//      engine, which is itself validated against a real certified-software
//      return; the real-figures parity test lives in the private repo)
{
  const r = computeReturn(corp("BC", "2025-03-01", "2025-12-31"), {
    revenue: 48250_75, openingInv: 0, purchases: 21400_00, closingInv: 6150_25,
    expenses: [
      { gifi: 9273, label: "Marketplace fees", amount: 9807_13 },
      { gifi: 9150, label: "Software", amount: 300_00 },
      { gifi: 9130, label: "Supplies", amount: 89_99 },
      { gifi: 9060, label: "Wages", amount: 12000_00 },
    ],
    cash: 4200_50, shareCapital: 100_00,
  });
  eq("Northpine net income", r.netIncome, 10803_88);
  eq("Northpine taxable", r.taxable, 10803_88);
  eq("Northpine federal", r.federal, 972_35);
  eq("Northpine provincial", r.provincial, 216_08);
  eq("Northpine total tax", r.total, 1188_43);
  eq("Northpine due-to-shareholder (negative = owner owes corp)", r.dueToShareholder, -553_13);
  eq("Northpine GIFI assets", r.gifi[2599], 10351);
  eq("Northpine GIFI liab+eq", r.gifi[3640], 10351);
  eq("Northpine GIFI 2780", r.gifi[2780], -553);
  eq("Northpine GIFI COGS", r.gifi[8518], 15250);
  eq("Northpine GIFI gross profit", r.gifi[8519], 33001);
  eq("Northpine GIFI opex", r.gifi[9367], 22197);
  eq("Northpine balances", r.balances, true);
}

// ---- provinces on $100k (fed always $9,000)
for (const [prov, want] of [
  ["BC", 2000_00], ["ON", 3200_00], ["MB", 0], ["SK", 1000_00],
  ["NB", 2500_00], ["NL", 2500_00], ["PE", 1000_00], ["YT", 0],
  ["NT", 2000_00], ["NU", 3000_00],
]) {
  const r = profitCase(prov, 100000_00);
  eq(`${prov} federal on 100k`, r.federal, 9000_00);
  eq(`${prov} provincial on 100k`, r.provincial, want);
}

// ---- Nova Scotia mid-year proration (2.5% -> 1.5% on 2025-04-01)
eq("NS 2025 prorated", profitCase("NS", 100000_00).provincial, 1746_58);
eq("NS post-change year", profitCase("NS", 100000_00,
  { start: "2025-05-01", end: "2026-04-30" }).provincial, 1500_00);
eq("NS 2024 leap year single rate", profitCase("NS", 100000_00,
  { start: "2024-01-01", end: "2024-12-31" }).provincial, 2500_00);

// ---- SBD limit edges
{
  const r = profitCase("BC", 600000_00);
  eq("BC 600k federal split", r.federal, 60000_00);
  eq("BC 600k provincial split", r.provincial, 22000_00);
  const s = profitCase("SK", 600000_00);
  eq("SK 600k uses $600k provincial limit", s.provincial, 6000_00);
}
eq("$1 profit total tax", profitCase("BC", 1_00).total, 11);
eq("one-day year", profitCase("BC", 1000_00,
  { start: "2025-06-01", end: "2025-06-01" }).total, 110_00);

// ---- Schedule 8
{
  const s = computeSchedule8([{ ccaClass: "50", openingUcc: 0, additions: 10000_00, dispositions: 0 }], "2025-12-31");
  eq("class 50 AccII full rate", s.cca, 5500_00);
  eq("class 50 closing UCC", s.classes[0].closingUcc, 4500_00);
  const h = computeSchedule8([{ ccaClass: "8", openingUcc: 0, additions: 10000_00, dispositions: 0 }], "2028-12-31");
  eq("class 8 half-year post-AccII", h.cca, 1000_00);
  const rc = computeSchedule8([{ ccaClass: "8", openingUcc: 1000_00, additions: 0, dispositions: 5000_00 }], "2025-12-31");
  eq("recapture", rc.recapture, 4000_00);
  const tl = computeSchedule8([{ ccaClass: "8", openingUcc: 3000_00, additions: 0, dispositions: 0, classEmptied: true }], "2025-12-31");
  eq("terminal loss", tl.terminalLoss, 3000_00);
  const c12 = computeSchedule8([{ ccaClass: "12", openingUcc: 0, additions: 800_00, dispositions: 0 }], "2025-12-31");
  eq("class 12 full write-off", c12.cca, 800_00);
  const pool = computeSchedule8([{ ccaClass: "10", openingUcc: 20000_00, additions: 0, dispositions: 0 }], "2025-12-31");
  eq("class 10 on opening pool", pool.cca, 6000_00);
}

// ---- Schedule 1
{
  const none = computeSchedule8([], "2025-12-31");
  eq("meals 50% addback",
     computeSchedule1(10000_00, { bookAmortization: 0, mealsTotal: 2000_00, penalties: 0 }, none).netIncomeForTax,
     11000_00);
  const s8 = computeSchedule8([{ ccaClass: "50", openingUcc: 0, additions: 10000_00, dispositions: 0 }], "2025-12-31");
  eq("amortization addback + CCA deduct",
     computeSchedule1(50000_00, { bookAmortization: 3000_00, mealsTotal: 0, penalties: 0 }, s8).netIncomeForTax,
     47500_00);
}

// ---- Schedule 4
{
  const [ti, app] = applyLosses(60000_00, 40000_00);
  eq("losses applied", ti, 20000_00);
  eq("losses exhausted", app.closing, 0);
  const r = profitCase("BC", 100000_00, { fin: { openingLosses: 40000_00 } });
  eq("return with losses: taxable", r.taxable, 60000_00);
  eq("return with losses: tax", r.total, 6600_00);
}

// ---- grinds
eq("taxable-capital grind midpoint", groundLimit(500000_00, 30000000_00, 0), 250000_00);
eq("passive grind", groundLimit(500000_00, 0, 100000_00), 250000_00);
{
  const r = profitCase("BC", 300000_00, { fin: { aaii: 100000_00 } });
  eq("passive grind fed", r.federal, 30000_00);
  eq("passive grind BC prov", r.provincial, 11000_00);
  const o = profitCase("ON", 300000_00, { fin: { aaii: 100000_00 } });
  eq("ON does not parallel passive grind", o.provincial, 9600_00);
}

// ---- end-to-end CCA return (matches Python integration test)
{
  const r = computeReturn(corp(), {
    revenue: 100000_00, openingInv: 0, purchases: 0, closingInv: 0,
    expenses: [], cash: 100000_00, shareCapital: 100_00,
    capitalAssets: [{ ccaClass: "50", openingUcc: 0, additions: 10000_00, dispositions: 0 }],
    bookAmortization: 3000_00,
  });
  eq("CCA return book income", r.netIncome, 97000_00);
  eq("CCA return income for tax", r.netIncomeForTax, 94500_00);
  eq("CCA return tax", r.total, 10395_00);
  eq("CCA return UCC on sheet", r.gifi[1740], 4500);
  eq("CCA return balances", r.balances, true);
}

// ---- breakeven + meals through the full return
{
  const r = computeReturn(corp(), {
    revenue: 1000_00, openingInv: 0, purchases: 0, closingInv: 0,
    expenses: [{ gifi: 9270, label: "Opex", amount: 1000_00 }],
    cash: 0, shareCapital: 1_00,
  });
  eq("breakeven tax", r.total, 0);
  eq("breakeven no phantom loss", r.nonCapitalLoss, 0);
  const m = computeReturn(corp(), {
    revenue: 50000_00, openingInv: 0, purchases: 0, closingInv: 0,
    expenses: [{ gifi: 8523, label: "Meals", amount: 2000_00 }],
    cash: 50000_00, shareCapital: 100_00, mealsTotal: 2000_00,
  });
  eq("meals books income", m.netIncome, 48000_00);
  eq("meals income for tax", m.netIncomeForTax, 49000_00);
}

// ---- scope guard
eq("QC declined", checkScope({ province: "QC" }).length > 0, true);
eq("clean BC supported", checkScope({ province: "BC" }).length, 0);
eq("dividends received declined", checkScope({ province: "BC", dividendsReceived: true }).length, 1);

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
